services:
  chatterbox-postgres:
    image: postgres:16-alpine
    container_name: chatterbox-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - chatterbox-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatterbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chatterbox-nginx:
    container_name: chatterbox-nginx
    image: nginx:1.27-alpine
    restart: always
    ports:
      - "8080:80"
      - "8081:81"
      - "8082:82"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chatterbox-network
    depends_on:
      - chatterbox-chat
      - chatterbox-notification

  chatterbox-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: chatterbox-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_NODENAME: rabbit@chatterbox-rabbitmq
    volumes:
      - chatterbox-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - chatterbox-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10

  chatterbox-chat:
    image: vaross/private-projects:chatterbox-chat-latest
    container_name: chatterbox-chat
    depends_on:
      chatterbox-rabbitmq:
        condition: service_healthy
      chatterbox-postgres:
        condition: service_healthy
    volumes:
      - ./chat/migrations:/srv/migrations
    env_file:
      - ./chat/.env
    networks:
      - chatterbox-network

  chatterbox-notification:
    image: vaross/private-projects:chatterbox-notification-latest
    container_name: chatterbox-notification
    depends_on:
      chatterbox-rabbitmq:
        condition: service_healthy
    env_file:
      - ./notification/.env
    networks:
      - chatterbox-network

  chatterbox-user:
    image: vaross/private-projects:chatterbox-user-latest
    container_name: chatterbox-user
    depends_on:
      chatterbox-postgres:
        condition: service_healthy
    volumes:
      - ./user/migrations:/srv/migrations
    env_file:
      - ./user/.env
    networks:
      - chatterbox-network

volumes:
  chatterbox-postgres-data:
  chatterbox-rabbitmq-data:

networks:
  chatterbox-network:
    name: chatterbox-network
    driver: bridge
