global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "chat"
    static_configs:
      - targets: ["chatterbox-chat:8080"]

  - job_name: "notification"
    static_configs:
      - targets: ["chatterbox-notification:8080"]

  - job_name: "user"
    static_configs:
      - targets: ["chatterbox-user:8080"]
