// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/chat/internal/domain/event"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventProducer creates a new instance of MockEventProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventProducer {
	mock := &MockEventProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventProducer is an autogenerated mock type for the EventProducer type
type MockEventProducer struct {
	mock.Mock
}

type MockEventProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventProducer) EXPECT() *MockEventProducer_Expecter {
	return &MockEventProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function for the type MockEventProducer
func (_mock *MockEventProducer) Produce(ctx context.Context, events ...event.Event) error {
	var tmpRet mock.Arguments
	if len(events) > 0 {
		tmpRet = _mock.Called(ctx, events)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...event.Event) error); ok {
		r0 = returnFunc(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockEventProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...event.Event
func (_e *MockEventProducer_Expecter) Produce(ctx any, events ...any) *MockEventProducer_Produce_Call {
	return &MockEventProducer_Produce_Call{Call: _e.mock.On("Produce",
		append([]any{ctx}, events...)...)}
}

func (_c *MockEventProducer_Produce_Call) Run(run func(ctx context.Context, events ...event.Event)) *MockEventProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []event.Event
		var variadicArgs []event.Event
		if len(args) > 1 {
			variadicArgs = args[1].([]event.Event)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockEventProducer_Produce_Call) Return(err error) *MockEventProducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventProducer_Produce_Call) RunAndReturn(run func(ctx context.Context, events ...event.Event) error) *MockEventProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}
