// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/chat/internal/domain/entity"
	"chatterbox/chat/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageRepo creates a new instance of MockMessageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepo {
	mock := &MockMessageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageRepo is an autogenerated mock type for the MessageRepo type
type MockMessageRepo struct {
	mock.Mock
}

type MockMessageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepo) EXPECT() *MockMessageRepo_Expecter {
	return &MockMessageRepo_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) List(ctx context.Context, chatID valueobject.ChatID) ([]*entity.Message, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.ChatID) ([]*entity.Message, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.ChatID) []*entity.Message); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.ChatID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMessageRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID valueobject.ChatID
func (_e *MockMessageRepo_Expecter) List(ctx any, chatID any) *MockMessageRepo_List_Call {
	return &MockMessageRepo_List_Call{Call: _e.mock.On("List", ctx, chatID)}
}

func (_c *MockMessageRepo_List_Call) Run(run func(ctx context.Context, chatID valueobject.ChatID)) *MockMessageRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.ChatID
		if args[1] != nil {
			arg1 = args[1].(valueobject.ChatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_List_Call) Return(messages []*entity.Message, err error) *MockMessageRepo_List_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepo_List_Call) RunAndReturn(run func(ctx context.Context, chatID valueobject.ChatID) ([]*entity.Message, error)) *MockMessageRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) Save(ctx context.Context, msg *entity.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMessageRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *entity.Message
func (_e *MockMessageRepo_Expecter) Save(ctx any, msg any) *MockMessageRepo_Save_Call {
	return &MockMessageRepo_Save_Call{Call: _e.mock.On("Save", ctx, msg)}
}

func (_c *MockMessageRepo_Save_Call) Run(run func(ctx context.Context, msg *entity.Message)) *MockMessageRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Message
		if args[1] != nil {
			arg1 = args[1].(*entity.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_Save_Call) Return(err error) *MockMessageRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepo_Save_Call) RunAndReturn(run func(ctx context.Context, msg *entity.Message) error) *MockMessageRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
