// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/chat/internal/domain/entity"
	"chatterbox/chat/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRepo creates a new instance of MockChatRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRepo {
	mock := &MockChatRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRepo is an autogenerated mock type for the ChatRepo type
type MockChatRepo struct {
	mock.Mock
}

type MockChatRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRepo) EXPECT() *MockChatRepo_Expecter {
	return &MockChatRepo_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) FindByID(ctx context.Context, chatID valueobject.ChatID) (*entity.Chat, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.ChatID) (*entity.Chat, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.ChatID) *entity.Chat); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.ChatID) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockChatRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID valueobject.ChatID
func (_e *MockChatRepo_Expecter) FindByID(ctx any, chatID any) *MockChatRepo_FindByID_Call {
	return &MockChatRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, chatID)}
}

func (_c *MockChatRepo_FindByID_Call) Run(run func(ctx context.Context, chatID valueobject.ChatID)) *MockChatRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.ChatID
		if args[1] != nil {
			arg1 = args[1].(valueobject.ChatID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepo_FindByID_Call) Return(chat *entity.Chat, err error) *MockChatRepo_FindByID_Call {
	_c.Call.Return(chat, err)
	return _c
}

func (_c *MockChatRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, chatID valueobject.ChatID) (*entity.Chat, error)) *MockChatRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) List(ctx context.Context, participantID valueobject.UserID) ([]*entity.Chat, error) {
	ret := _mock.Called(ctx, participantID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) ([]*entity.Chat, error)); ok {
		return returnFunc(ctx, participantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) []*entity.Chat); ok {
		r0 = returnFunc(ctx, participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, participantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockChatRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - participantID valueobject.UserID
func (_e *MockChatRepo_Expecter) List(ctx any, participantID any) *MockChatRepo_List_Call {
	return &MockChatRepo_List_Call{Call: _e.mock.On("List", ctx, participantID)}
}

func (_c *MockChatRepo_List_Call) Run(run func(ctx context.Context, participantID valueobject.UserID)) *MockChatRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepo_List_Call) Return(chats []*entity.Chat, err error) *MockChatRepo_List_Call {
	_c.Call.Return(chats, err)
	return _c
}

func (_c *MockChatRepo_List_Call) RunAndReturn(run func(ctx context.Context, participantID valueobject.UserID) ([]*entity.Chat, error)) *MockChatRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) Save(ctx context.Context, chat *entity.Chat) error {
	ret := _mock.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Chat) error); ok {
		r0 = returnFunc(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockChatRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - chat *entity.Chat
func (_e *MockChatRepo_Expecter) Save(ctx any, chat any) *MockChatRepo_Save_Call {
	return &MockChatRepo_Save_Call{Call: _e.mock.On("Save", ctx, chat)}
}

func (_c *MockChatRepo_Save_Call) Run(run func(ctx context.Context, chat *entity.Chat)) *MockChatRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Chat
		if args[1] != nil {
			arg1 = args[1].(*entity.Chat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepo_Save_Call) Return(err error) *MockChatRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRepo_Save_Call) RunAndReturn(run func(ctx context.Context, chat *entity.Chat) error) *MockChatRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
