// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/user/internal/domain/entity"
	"chatterbox/user/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenRepo creates a new instance of MockRefreshTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepo is an autogenerated mock type for the RefreshTokenRepo type
type MockRefreshTokenRepo struct {
	mock.Mock
}

type MockRefreshTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepo_Expecter {
	return &MockRefreshTokenRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) Get(ctx context.Context, id valueobject.TokenID) (*entity.RefreshToken, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TokenID) (*entity.RefreshToken, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TokenID) *entity.RefreshToken); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.TokenID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRefreshTokenRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.TokenID
func (_e *MockRefreshTokenRepo_Expecter) Get(ctx any, id any) *MockRefreshTokenRepo_Get_Call {
	return &MockRefreshTokenRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRefreshTokenRepo_Get_Call) Run(run func(ctx context.Context, id valueobject.TokenID)) *MockRefreshTokenRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.TokenID
		if args[1] != nil {
			arg1 = args[1].(valueobject.TokenID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Get_Call) Return(refreshToken *entity.RefreshToken, err error) *MockRefreshTokenRepo_Get_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id valueobject.TokenID) (*entity.RefreshToken, error)) *MockRefreshTokenRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) Revoke(ctx context.Context, id valueobject.TokenID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TokenID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRefreshTokenRepo_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.TokenID
func (_e *MockRefreshTokenRepo_Expecter) Revoke(ctx any, id any) *MockRefreshTokenRepo_Revoke_Call {
	return &MockRefreshTokenRepo_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockRefreshTokenRepo_Revoke_Call) Run(run func(ctx context.Context, id valueobject.TokenID)) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.TokenID
		if args[1] != nil {
			arg1 = args[1].(valueobject.TokenID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Revoke_Call) Return(err error) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_Revoke_Call) RunAndReturn(run func(ctx context.Context, id valueobject.TokenID) error) *MockRefreshTokenRepo_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRefreshTokenRepo
func (_mock *MockRefreshTokenRepo) Save(ctx context.Context, token *entity.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRefreshTokenRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - token *entity.RefreshToken
func (_e *MockRefreshTokenRepo_Expecter) Save(ctx any, token any) *MockRefreshTokenRepo_Save_Call {
	return &MockRefreshTokenRepo_Save_Call{Call: _e.mock.On("Save", ctx, token)}
}

func (_c *MockRefreshTokenRepo_Save_Call) Run(run func(ctx context.Context, token *entity.RefreshToken)) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entity.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) Return(err error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepo_Save_Call) RunAndReturn(run func(ctx context.Context, token *entity.RefreshToken) error) *MockRefreshTokenRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
