// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordVerifier creates a new instance of MockPasswordVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordVerifier {
	mock := &MockPasswordVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type MockPasswordVerifier struct {
	mock.Mock
}

type MockPasswordVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordVerifier) EXPECT() *MockPasswordVerifier_Expecter {
	return &MockPasswordVerifier_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockPasswordVerifier
func (_mock *MockPasswordVerifier) Compare(hash string, password string) bool {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPasswordVerifier_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockPasswordVerifier_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockPasswordVerifier_Expecter) Compare(hash any, password any) *MockPasswordVerifier_Compare_Call {
	return &MockPasswordVerifier_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *MockPasswordVerifier_Compare_Call) Run(run func(hash string, password string)) *MockPasswordVerifier_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordVerifier_Compare_Call) Return(b bool) *MockPasswordVerifier_Compare_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPasswordVerifier_Compare_Call) RunAndReturn(run func(hash string, password string) bool) *MockPasswordVerifier_Compare_Call {
	_c.Call.Return(run)
	return _c
}
