// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/user/internal/domain/entity"
	"chatterbox/user/internal/domain/valueobject"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// ExistsByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) ExistsByEmail(ctx context.Context, email valueobject.Email) bool {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.Email) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUserRepo_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockUserRepo_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email valueobject.Email
func (_e *MockUserRepo_Expecter) ExistsByEmail(ctx any, email any) *MockUserRepo_ExistsByEmail_Call {
	return &MockUserRepo_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockUserRepo_ExistsByEmail_Call) Run(run func(ctx context.Context, email valueobject.Email)) *MockUserRepo_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.Email
		if args[1] != nil {
			arg1 = args[1].(valueobject.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_ExistsByEmail_Call) Return(b bool) *MockUserRepo_ExistsByEmail_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUserRepo_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email valueobject.Email) bool) *MockUserRepo_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByEmail(ctx context.Context, email valueobject.Email) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.Email) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.Email) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.Email) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepo_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email valueobject.Email
func (_e *MockUserRepo_Expecter) FindByEmail(ctx any, email any) *MockUserRepo_FindByEmail_Call {
	return &MockUserRepo_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepo_FindByEmail_Call) Run(run func(ctx context.Context, email valueobject.Email)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.Email
		if args[1] != nil {
			arg1 = args[1].(valueobject.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) Return(user *entity.User, err error) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email valueobject.Email) (*entity.User, error)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByID(ctx context.Context, id valueobject.UserID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.UserID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.UserID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.UserID
func (_e *MockUserRepo_Expecter) FindByID(ctx any, id any) *MockUserRepo_FindByID_Call {
	return &MockUserRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepo_FindByID_Call) Run(run func(ctx context.Context, id valueobject.UserID)) *MockUserRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByID_Call) Return(user *entity.User, err error) *MockUserRepo_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id valueobject.UserID) (*entity.User, error)) *MockUserRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) List(ctx context.Context, userIDs []valueobject.UserID, limit int, offset int) ([]*entity.User, error) {
	ret := _mock.Called(ctx, userIDs, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []valueobject.UserID, int, int) ([]*entity.User, error)); ok {
		return returnFunc(ctx, userIDs, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []valueobject.UserID, int, int) []*entity.User); ok {
		r0 = returnFunc(ctx, userIDs, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []valueobject.UserID, int, int) error); ok {
		r1 = returnFunc(ctx, userIDs, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []valueobject.UserID
//   - limit int
//   - offset int
func (_e *MockUserRepo_Expecter) List(ctx any, userIDs any, limit any, offset any) *MockUserRepo_List_Call {
	return &MockUserRepo_List_Call{Call: _e.mock.On("List", ctx, userIDs, limit, offset)}
}

func (_c *MockUserRepo_List_Call) Run(run func(ctx context.Context, userIDs []valueobject.UserID, limit int, offset int)) *MockUserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].([]valueobject.UserID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_List_Call) Return(users []*entity.User, err error) *MockUserRepo_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_List_Call) RunAndReturn(run func(ctx context.Context, userIDs []valueobject.UserID, limit int, offset int) ([]*entity.User, error)) *MockUserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Save(ctx context.Context, user *entity.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) Save(ctx any, user any) *MockUserRepo_Save_Call {
	return &MockUserRepo_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *MockUserRepo_Save_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Save_Call) Return(err error) *MockUserRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Save_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) error) *MockUserRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
