// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/user/internal/domain/port"
	"chatterbox/user/internal/domain/valueobject"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenVerifier creates a new instance of MockTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenVerifier {
	mock := &MockTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenVerifier is an autogenerated mock type for the TokenVerifier type
type MockTokenVerifier struct {
	mock.Mock
}

type MockTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenVerifier) EXPECT() *MockTokenVerifier_Expecter {
	return &MockTokenVerifier_Expecter{mock: &_m.Mock}
}

// VerifyAccess provides a mock function for the type MockTokenVerifier
func (_mock *MockTokenVerifier) VerifyAccess(token string) (*port.AccessTokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccess")
	}

	var r0 *port.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*port.AccessTokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *port.AccessTokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenVerifier_VerifyAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccess'
type MockTokenVerifier_VerifyAccess_Call struct {
	*mock.Call
}

// VerifyAccess is a helper method to define mock.On call
//   - token string
func (_e *MockTokenVerifier_Expecter) VerifyAccess(token any) *MockTokenVerifier_VerifyAccess_Call {
	return &MockTokenVerifier_VerifyAccess_Call{Call: _e.mock.On("VerifyAccess", token)}
}

func (_c *MockTokenVerifier_VerifyAccess_Call) Run(run func(token string)) *MockTokenVerifier_VerifyAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenVerifier_VerifyAccess_Call) Return(accessTokenClaims *port.AccessTokenClaims, err error) *MockTokenVerifier_VerifyAccess_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockTokenVerifier_VerifyAccess_Call) RunAndReturn(run func(token string) (*port.AccessTokenClaims, error)) *MockTokenVerifier_VerifyAccess_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRefresh provides a mock function for the type MockTokenVerifier
func (_mock *MockTokenVerifier) VerifyRefresh(token string) (valueobject.TokenID, valueobject.UserID, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRefresh")
	}

	var r0 valueobject.TokenID
	var r1 valueobject.UserID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (valueobject.TokenID, valueobject.UserID, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) valueobject.TokenID); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(valueobject.TokenID)
	}
	if returnFunc, ok := ret.Get(1).(func(string) valueobject.UserID); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Get(1).(valueobject.UserID)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenVerifier_VerifyRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRefresh'
type MockTokenVerifier_VerifyRefresh_Call struct {
	*mock.Call
}

// VerifyRefresh is a helper method to define mock.On call
//   - token string
func (_e *MockTokenVerifier_Expecter) VerifyRefresh(token any) *MockTokenVerifier_VerifyRefresh_Call {
	return &MockTokenVerifier_VerifyRefresh_Call{Call: _e.mock.On("VerifyRefresh", token)}
}

func (_c *MockTokenVerifier_VerifyRefresh_Call) Run(run func(token string)) *MockTokenVerifier_VerifyRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenVerifier_VerifyRefresh_Call) Return(tokenID valueobject.TokenID, userID valueobject.UserID, err error) *MockTokenVerifier_VerifyRefresh_Call {
	_c.Call.Return(tokenID, userID, err)
	return _c
}

func (_c *MockTokenVerifier_VerifyRefresh_Call) RunAndReturn(run func(token string) (valueobject.TokenID, valueobject.UserID, error)) *MockTokenVerifier_VerifyRefresh_Call {
	_c.Call.Return(run)
	return _c
}
