// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"chatterbox/user/internal/domain/valueobject"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenSigner creates a new instance of MockTokenSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenSigner {
	mock := &MockTokenSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenSigner is an autogenerated mock type for the TokenSigner type
type MockTokenSigner struct {
	mock.Mock
}

type MockTokenSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenSigner) EXPECT() *MockTokenSigner_Expecter {
	return &MockTokenSigner_Expecter{mock: &_m.Mock}
}

// SignAccess provides a mock function for the type MockTokenSigner
func (_mock *MockTokenSigner) SignAccess(userID valueobject.UserID, now time.Time) (string, error) {
	ret := _mock.Called(userID, now)

	if len(ret) == 0 {
		panic("no return value specified for SignAccess")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(valueobject.UserID, time.Time) (string, error)); ok {
		return returnFunc(userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(valueobject.UserID, time.Time) string); ok {
		r0 = returnFunc(userID, now)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(valueobject.UserID, time.Time) error); ok {
		r1 = returnFunc(userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenSigner_SignAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAccess'
type MockTokenSigner_SignAccess_Call struct {
	*mock.Call
}

// SignAccess is a helper method to define mock.On call
//   - userID valueobject.UserID
//   - now time.Time
func (_e *MockTokenSigner_Expecter) SignAccess(userID any, now any) *MockTokenSigner_SignAccess_Call {
	return &MockTokenSigner_SignAccess_Call{Call: _e.mock.On("SignAccess", userID, now)}
}

func (_c *MockTokenSigner_SignAccess_Call) Run(run func(userID valueobject.UserID, now time.Time)) *MockTokenSigner_SignAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 valueobject.UserID
		if args[0] != nil {
			arg0 = args[0].(valueobject.UserID)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenSigner_SignAccess_Call) Return(s string, err error) *MockTokenSigner_SignAccess_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenSigner_SignAccess_Call) RunAndReturn(run func(userID valueobject.UserID, now time.Time) (string, error)) *MockTokenSigner_SignAccess_Call {
	_c.Call.Return(run)
	return _c
}

// SignRefresh provides a mock function for the type MockTokenSigner
func (_mock *MockTokenSigner) SignRefresh(tokenID valueobject.TokenID, userID valueobject.UserID, now time.Time) (string, error) {
	ret := _mock.Called(tokenID, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for SignRefresh")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(valueobject.TokenID, valueobject.UserID, time.Time) (string, error)); ok {
		return returnFunc(tokenID, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(valueobject.TokenID, valueobject.UserID, time.Time) string); ok {
		r0 = returnFunc(tokenID, userID, now)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(valueobject.TokenID, valueobject.UserID, time.Time) error); ok {
		r1 = returnFunc(tokenID, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenSigner_SignRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignRefresh'
type MockTokenSigner_SignRefresh_Call struct {
	*mock.Call
}

// SignRefresh is a helper method to define mock.On call
//   - tokenID valueobject.TokenID
//   - userID valueobject.UserID
//   - now time.Time
func (_e *MockTokenSigner_Expecter) SignRefresh(tokenID any, userID any, now any) *MockTokenSigner_SignRefresh_Call {
	return &MockTokenSigner_SignRefresh_Call{Call: _e.mock.On("SignRefresh", tokenID, userID, now)}
}

func (_c *MockTokenSigner_SignRefresh_Call) Run(run func(tokenID valueobject.TokenID, userID valueobject.UserID, now time.Time)) *MockTokenSigner_SignRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 valueobject.TokenID
		if args[0] != nil {
			arg0 = args[0].(valueobject.TokenID)
		}
		var arg1 valueobject.UserID
		if args[1] != nil {
			arg1 = args[1].(valueobject.UserID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenSigner_SignRefresh_Call) Return(s string, err error) *MockTokenSigner_SignRefresh_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenSigner_SignRefresh_Call) RunAndReturn(run func(tokenID valueobject.TokenID, userID valueobject.UserID, now time.Time) (string, error)) *MockTokenSigner_SignRefresh_Call {
	_c.Call.Return(run)
	return _c
}
